  - name: Profile Readme Chess Rating Chart
  # You may pin to the exact commit or the version.
  # uses: mmzeynalli/chess-rating-chart@266e94b310b22b02484f50d4516c5ad7b3870622
  uses: mmzeynalli/chess-rating-chart@v1.0.1
  with:
    # GitHub access token with Repo scope
    GH_TOKEN: # default is ${{ github.token }}
    # Chess.com username
    CHESS_COM_USERNAME: "OzzyKPH2007" 
    # Chess.com time class to graph ("daily", "rapid", "blitz", "bullet")
    CHESS_COM_TIME_CLASS: "rapid"

    LAST_N_GAMES: # optional, default is 100
    # Chart height
    RATING_CHART_HEIGHT: # optional, default is 20
    # Push branch name
    PUSH_BRANCH_NAME: # optional, default is main
    # Whether to commit by user (True) or github-actions bot (False)
    COMMIT_BY_ME: # optional, default is False
    # Commit message
    COMMIT_MESSAGE: # optional, default is Updated the chess rating graph
    # Debug logging
    DEBUG_LOGGING: # optional, default is False
    # Debug run
    DEBUG_RUN: # optional, default is False
          
